<?php

/*
 * Copyright (c) 2003-2025, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

/**
 * @file
 * Contains CKEditor 5 Premium Features Merge Fields module functions.
 */

declare(strict_types = 1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\ckeditor5_premium_features_merge_fields\MergeFieldsProcessor;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_merge_fields_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $library = new LibraryDefinitionItem('merge-fields', $config_handler->getDllLocation());
  $library->addRemoteJs($library->id());
  $library->addDependency('core/ckeditor5.image');

  $libraries[$library->id()] = $library->getDefinition();

  return $libraries;
}

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_premium_features_merge_fields_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $info['text_format']['#process'][] = [MergeFieldsProcessor::class, 'process'];
  }
}
