ui_patterns_source.field_formatter:*:*:*:
  type: mapping
  label: 'Source: field_formatter'
  mapping:
    type:
      type: string
      label: 'Field formatter type'
    settings:
      type: field.formatter.settings.[%parent.type]
      label: 'Field formatter settings'
    third_party_settings:
      # Third party settings are always optional: they're an optional extension
      # point.
      requiredKey: false
      type: sequence
      label: 'Third party settings'
      sequence:
        type: field.formatter.third_party.[%key]
