paragraph_blocks.settings:
  type: config_object
  label: 'Paragraph blocks settings'
  mapping:
    max_cardinality:
      type: integer
      label: 'Max Cardinality to display in the UI for placement'
    individual_block_ui:
      type: boolean
      label: 'Display individual paragraph blocks in the UI'
    suppress_label:
      type: boolean
      label: 'Whether to show the label field on layout manager block placement'

field.field.*.*.*.third_party.paragraph_blocks:
  type: mapping
  label: 'Paragraph blocks configuration'
  mapping:
    status:
      type: integer
      label: 'Paragraph blocks enabled'
